# Ejercicios Python 2

Resuelve cada ejercicio en su celda y añade las pruebas necesarias para comprobar que funciona correctamente. Indica en un comentario la dificultad encontrada (del 1 al 5).

In [2]:
import numpy as np

In [19]:
# Función que recibe una lista y devuelve otra eliminando sus duplicados (función y pruebas)
def eliminar_duplicados(lista):
    lista_nueva = set(lista)
    return lista_nueva

lista= [1,2,3,1,2,3,4,5,6]
print(eliminar_duplicados(lista))

#Dificultad = 1

#Con numpy
def eliminar_duplicados_np(lista):
    lista = list(np.unique(lista))
    return lista


eliminar_duplicados_np(lista)

#Dificultad = 1

{1, 2, 3, 4, 5, 6}


[1, 2, 3, 4, 5, 6]

In [29]:
# Función que recibe una matriz (una lista de listas) y devuelve otra eliminando sus duplicados
def matriz_sin_duplicados(matriz):
    #Creamos una lista de conjuntos vacía para ir agregando y comparar
    lista_set = set()
    
    #Aqui almacenamos resultado
    lista_resultado = []

    for fila in matriz:
        lista_tupla = tuple(fila)
        if lista_tupla not in lista_set:
            lista_set.add(lista_tupla)
            lista_resultado.append(fila)
    
    return lista_resultado
    
        

matriz = [[1,2,3],[1,2,3],[4,5,6],[7,8,9]]
print(matriz_sin_duplicados(matriz))

#Dificultad = 3

#Con numpy
def matriz_sin_duplicados_np(matriz):
    matriz_unica = np.unique(matriz)
    matriz = np.array(matriz_unica)    #Convertimos la lista de listas en array de verdad :)
    return matriz

matriz_sin_duplicados_np(matriz)

#Dificultad = 1

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
# Función que recibe una lista y devuelve un diccionario con el número de veces que aparece cada elemento (las claves del diccionario deben ser los elementos de la lista y los valores deben ser el número de veces que aparece dicho elemento en la lista)
def convertir_diccionario(lista):
    diccionario = {}

    for elemento in lista:
        if elemento not in diccionario.keys():
            diccionario[elemento] = 1
        else:
            diccionario[elemento] += 1
    print(diccionario)

lista = [1,2,3,4,1,2,3,4,5,6,7,1,2,3,1,2,3]
convertir_diccionario(lista)

#Dificultad = 2

#Numpy
def convertir_diccionario_np(lista):
    lista = dict(zip(*np.unique(lista,return_counts=True)))

    return lista

convertir_diccionario_np(lista)
#Dificultad = 5 no sacaba el asterisco 

{1: 4, 2: 4, 3: 4, 4: 2, 5: 1, 6: 1, 7: 1}


{1: 4, 2: 4, 3: 4, 4: 2, 5: 1, 6: 1, 7: 1}

In [60]:
# Función que recibe dos matrices cuadradas (NxN) y devuelve una tercera matriz que contiene el valor 1 en las posiciones en que el valor de A y B coinciden y 0 en caso contrario.
def valores_iguales_matriz(matriz1, matriz2):
    # Verificar si las matrices son cuadradas
    if len(matriz1) != len(matriz2):
        print("Error las matrices no son cuadradas")

    # Inicializar la matriz resultado
    matriz_final = []
    for fila in range(len(matriz1)):
        fila_final = []
        for elemento in range(len(matriz1)):
            if matriz1[fila][elemento] == matriz2[fila][elemento]:
                fila_final.append(1)
            else:
                fila_final.append(0)
        matriz_final.append(fila_final)
    return matriz_final

# Tests
matriz1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] # Matriz 3x3
matriz2 = [[1, 5, 6], [7, 5, 9], [1, 2, 9]] # Matriz 3x3
print(valores_iguales_matriz(matriz1, matriz2)) # Debería mostrar una matriz identidad
assert valores_iguales_matriz(matriz1, matriz2) == [[1, 0, 0], [0, 1, 0], [0, 0, 1]]


'''
La sentencia assert evalúa una expresión booleana. Si es True, no hace nada. Si es False, lanza una excepción de tipo AssertionError.
Si tu función es correcta, al ejecutar no debería mostrar nada. Si falla, mostrará un AssertionError.
Se utiliza para testing. 
https://ellibrodepython.com/assert-python
'''
#Dificultad = 4

#Numpy 
def valores_iguales_matriz_np(matriz3,matriz4):
    matriz = np.where(matriz3 == matriz4 ,1 ,0)
    return matriz

    
matriz3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
matriz4 = np.array([[1, 5, 6], [7, 5, 9], [1, 2, 9]]) 
print(valores_iguales_matriz_np(matriz3, matriz4)) 

#Dificultad = 3

[[1, 0, 0], [0, 1, 0], [0, 0, 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [7]:
# Función que recibe una matriz y busca sus puntos de silla (mínimo de su fila y máximo de su columna o viceversa). Debe devolver una lista de tuplas con las coordenadas de los puntos de silla.
def puntos_de_silla(matriz):

    fila = len(matriz)
    columna = len(matriz[0])
    cordenadas= []

    for x in range(fila):
        for y in range(columna):
            elemento_actual = matriz[x][y]
            if elemento_actual == min(matriz[x]) and elemento_actual == max(matriz[k][y] for k in range(fila)):
                #print("minimo fila y maximo de columna:{}".format(elemento_actual))
                cordenadas.append((x,y))
            elif elemento_actual == max(matriz[x]) and elemento_actual == min(matriz[k][y] for k in range(fila)):
                #print("maximo de fila y minimo de fila:{}".format(elemento_actual))
                cordenadas.append((x,y))
    return cordenadas

matriz =[[1,2,3],[4,5,6],[7,8,9]]
puntos_de_silla(matriz)

#Dificultad = 5








[(0, 2), (2, 0)]

## 

In [9]:
#Numpy
import numpy as np

def puntos_de_silla_numpy(matriz):
    matriz = np.array(matriz)

    #indices minimos por fila
    indices_min_fila = np.argmin(matriz,axis=1)

    #indices maximos columna
    indices_max_columna = np.argmax(matriz,axis=0)
    
    #los puntos de silla comparando los indices anteriores
    puntos_silla_filas,puntos_silla_columnas = np.where(indices_min_fila[:,None] == indices_max_columna)
    print(puntos_silla_columnas,puntos_silla_filas)
    #Creamos lista

    puntos_silla = list(zip(puntos_silla_filas,puntos_silla_columnas))

    return puntos_silla

#matriz:
matriz_ejemplo = [[1,2,3],[4,5,6],[7,8,9]]

resultado = puntos_de_silla_numpy(matriz_ejemplo)
print("Puntos de silla: ",resultado)

[] []
Puntos de silla:  []


## 